#!/usr/bin/env node
/**
 * Calculate sunrise/sunset/golden hour for each day of the trip.
 * Outputs src/data/sun.ts with pre-calculated times.
 */

import SunCalc from 'suncalc';
import { writeFileSync } from 'fs';

// Trip: July 10-30, 2026
// Day centers (representative coordinates per day)
const days = [
  { day: 0,  lat: 40.1792, lng: 44.5126, tz: 4,  label: 'Ереван' },          // Armenia +4
  { day: 1,  lat: 40.7128, lng: -74.006, tz: -4,  label: 'Нью-Йорк' },
  { day: 2,  lat: 40.7128, lng: -74.006, tz: -4,  label: 'Нью-Йорк' },
  { day: 3,  lat: 40.7128, lng: -74.006, tz: -4,  label: 'Нью-Йорк' },
  { day: 4,  lat: 40.7128, lng: -74.006, tz: -4,  label: 'Нью-Йорк' },
  { day: 5,  lat: 36.1097, lng: -115.174, tz: -7, label: 'Лас-Вегас' },
  { day: 6,  lat: 37.2982, lng: -113.026, tz: -7, label: 'Zion' },
  { day: 7,  lat: 36.9833, lng: -110.114, tz: -7, label: 'Monument Valley' },
  { day: 8,  lat: 36.8619, lng: -111.374, tz: -7, label: 'Page / Antelope' },
  { day: 9,  lat: 36.0544, lng: -112.140, tz: -7, label: 'Grand Canyon' },
  { day: 10, lat: 35.328,  lng: -112.876, tz: -7, label: 'Route 66 → LA' },
  { day: 11, lat: 34.0211, lng: -118.397, tz: -7, label: 'Лос-Анджелес' },
  { day: 12, lat: 34.0211, lng: -118.397, tz: -7, label: 'Лос-Анджелес' },
  { day: 13, lat: 34.0211, lng: -118.397, tz: -7, label: 'Лос-Анджелес' },
  { day: 14, lat: 20.7984, lng: -156.332, tz: -10, label: 'Мауи' },
  { day: 15, lat: 20.7984, lng: -156.332, tz: -10, label: 'Мауи' },
  { day: 16, lat: 20.7984, lng: -156.332, tz: -10, label: 'Мауи' },
  { day: 17, lat: 20.7984, lng: -156.332, tz: -10, label: 'Мауи' },
  { day: 18, lat: 34.0211, lng: -118.397, tz: -7, label: 'Лос-Анджелес' },
  { day: 19, lat: 34.0211, lng: -118.397, tz: -7, label: 'Обратный рейс' },
];

function formatTime(date, tzOffset) {
  // SunCalc returns UTC, convert to local
  const local = new Date(date.getTime() + tzOffset * 3600000);
  const h = local.getUTCHours().toString().padStart(2, '0');
  const m = local.getUTCMinutes().toString().padStart(2, '0');
  return `${h}:${m}`;
}

const results = days.map(d => {
  const date = new Date(2026, 6, 10 + d.day); // July 10 + dayNumber
  const times = SunCalc.getTimes(date, d.lat, d.lng);

  return {
    dayNumber: d.day,
    sunrise: formatTime(times.sunrise, d.tz),
    sunset: formatTime(times.sunset, d.tz),
    goldenHourStart: formatTime(times.goldenHour, d.tz),
    goldenHourEnd: formatTime(times.sunset, d.tz),
  };
});

// Generate TypeScript file
const ts = `// Auto-generated by scripts/calc-sun.mjs — do not edit manually
// Sunrise/sunset times for July 10-30, 2026

export interface SunTimes {
  sunrise: string;
  sunset: string;
  goldenHourStart: string;
}

export const sunData: Record<number, SunTimes> = {
${results.map(r => `  ${r.dayNumber}: { sunrise: '${r.sunrise}', sunset: '${r.sunset}', goldenHourStart: '${r.goldenHourStart}' },`).join('\n')}
};
`;

writeFileSync('src/data/sun.ts', ts);

// Print for verification
console.log('Day | Location         | Sunrise | Sunset | Golden Hour');
console.log('----|------------------|---------|--------|------------');
results.forEach((r, i) => {
  console.log(`${String(r.dayNumber).padStart(3)} | ${days[i].label.padEnd(16)} | ${r.sunrise}   | ${r.sunset}  | ${r.goldenHourStart}`);
});
