#!/usr/bin/env node
/**
 * Fetches historical weather for trip dates (avg of 2023-2025)
 * and generates src/data/weather.ts
 */

import { writeFileSync } from 'fs';

const DAYS = [
  { day: 0, lat: 40.18, lng: 44.51, date: '07-10', name: 'Yerevan' },
  { day: 1, lat: 40.71, lng: -74.01, date: '07-11', name: 'NYC' },
  { day: 2, lat: 40.71, lng: -74.01, date: '07-12', name: 'NYC' },
  { day: 3, lat: 40.71, lng: -74.01, date: '07-13', name: 'NYC' },
  { day: 4, lat: 40.71, lng: -74.01, date: '07-14', name: 'NYC' },
  { day: 5, lat: 36.11, lng: -115.17, date: '07-15', name: 'Vegas' },
  { day: 6, lat: 37.30, lng: -113.03, date: '07-16', name: 'Zion' },
  { day: 7, lat: 36.98, lng: -110.11, date: '07-17', name: 'Mon.Valley' },
  { day: 8, lat: 36.86, lng: -111.37, date: '07-18', name: 'Page' },
  { day: 9, lat: 36.05, lng: -112.14, date: '07-19', name: 'GrandCanyon' },
  { day: 10, lat: 35.33, lng: -112.88, date: '07-20', name: 'Route66' },
  { day: 11, lat: 34.02, lng: -118.40, date: '07-21', name: 'LA' },
  { day: 12, lat: 34.02, lng: -118.40, date: '07-22', name: 'LA' },
  { day: 13, lat: 34.02, lng: -118.40, date: '07-23', name: 'LA' },
  { day: 14, lat: 20.80, lng: -156.33, date: '07-24', name: 'Maui' },
  { day: 15, lat: 20.80, lng: -156.33, date: '07-25', name: 'Maui' },
  { day: 16, lat: 20.80, lng: -156.33, date: '07-26', name: 'Maui' },
  { day: 17, lat: 20.80, lng: -156.33, date: '07-27', name: 'Maui' },
  { day: 18, lat: 34.02, lng: -118.40, date: '07-28', name: 'LA' },
  { day: 19, lat: 34.02, lng: -118.40, date: '07-29', name: 'LA' },
];

const WMO = {
  0: { icon: '☀️', desc: 'Ясно' },
  1: { icon: '🌤️', desc: 'Малооблачно' },
  2: { icon: '⛅', desc: 'Облачно' },
  3: { icon: '☁️', desc: 'Пасмурно' },
  45: { icon: '🌫️', desc: 'Туман' },
  51: { icon: '🌦️', desc: 'Морось' },
  53: { icon: '🌧️', desc: 'Дождь' },
  61: { icon: '🌧️', desc: 'Дождь' },
  80: { icon: '🌦️', desc: 'Ливень' },
  95: { icon: '⛈️', desc: 'Гроза' },
};

function getWmo(code) {
  return WMO[code] || WMO[Math.floor(code / 10) * 10] || { icon: '🌡️', desc: '' };
}

async function fetchYear(day, year) {
  const dateStr = `${year}-${day.date}`;
  const url = `https://archive-api.open-meteo.com/v1/archive?latitude=${day.lat}&longitude=${day.lng}&daily=temperature_2m_max,temperature_2m_min,weather_code&start_date=${dateStr}&end_date=${dateStr}&timezone=auto`;
  const res = await fetch(url);
  const data = await res.json();
  if (!data.daily) return null;
  return {
    max: data.daily.temperature_2m_max[0],
    min: data.daily.temperature_2m_min[0],
    code: data.daily.weather_code[0],
  };
}

async function main() {
  const results = {};
  const years = [2023, 2024, 2025];

  for (const day of DAYS) {
    const yearData = [];
    for (const year of years) {
      const d = await fetchYear(day, year);
      if (d) yearData.push(d);
      await new Promise(r => setTimeout(r, 100));
    }

    if (yearData.length === 0) continue;

    const avgMax = Math.round(yearData.reduce((s, d) => s + d.max, 0) / yearData.length);
    const avgMin = Math.round(yearData.reduce((s, d) => s + d.min, 0) / yearData.length);
    // Most common weather code
    const codes = yearData.map(d => d.code);
    const modeCode = codes.sort((a, b) =>
      codes.filter(v => v === a).length - codes.filter(v => v === b).length
    ).pop();

    const wmo = getWmo(modeCode);
    results[day.day] = { max: avgMax, min: avgMin, icon: wmo.icon, desc: wmo.desc };

    console.log(`Day ${day.day} (${day.name}): ${avgMin}–${avgMax}°C ${wmo.icon} ${wmo.desc}`);
  }

  const ts = `// Auto-generated by scripts/calc-weather.mjs
// Average weather for July trip dates (2023-2025 historical data)

export interface DayWeather {
  max: number;
  min: number;
  icon: string;
  desc: string;
}

export const weatherData: Record<number, DayWeather> = {
${Object.entries(results).map(([day, w]) =>
  `  ${day}: { max: ${w.max}, min: ${w.min}, icon: '${w.icon}', desc: '${w.desc}' },`
).join('\n')}
};
`;

  writeFileSync('src/data/weather.ts', ts);
  console.log('\nGenerated src/data/weather.ts');
}

main();
