// Auto-generated by scripts/calc-sun.mjs — do not edit manually
// Sunrise/sunset times for July 10-30, 2026

export interface SunTimes {
  sunrise: string;
  sunset: string;
  goldenHourStart: string;
}

export const sunData: Record<number, SunTimes> = {
  0: { sunrise: '05:42', sunset: '20:34', goldenHourStart: '19:54' },
  1: { sunrise: '05:35', sunset: '20:29', goldenHourStart: '19:49' },
  2: { sunrise: '05:35', sunset: '20:29', goldenHourStart: '19:48' },
  3: { sunrise: '05:36', sunset: '20:29', goldenHourStart: '19:48' },
  4: { sunrise: '05:37', sunset: '20:28', goldenHourStart: '19:48' },
  5: { sunrise: '05:35', sunset: '19:59', goldenHourStart: '19:22' },
  6: { sunrise: '05:24', sunset: '19:53', goldenHourStart: '19:15' },
  7: { sunrise: '05:14', sunset: '19:40', goldenHourStart: '19:02' },
  8: { sunrise: '05:20', sunset: '19:44', goldenHourStart: '19:07' },
  9: { sunrise: '05:26', sunset: '19:45', goldenHourStart: '19:08' },
  10: { sunrise: '05:31', sunset: '19:45', goldenHourStart: '19:09' },
  11: { sunrise: '05:57', sunset: '20:04', goldenHourStart: '19:28' },
  12: { sunrise: '05:58', sunset: '20:03', goldenHourStart: '19:27' },
  13: { sunrise: '05:59', sunset: '20:03', goldenHourStart: '19:27' },
  14: { sunrise: '05:57', sunset: '19:08', goldenHourStart: '18:37' },
  15: { sunrise: '05:57', sunset: '19:08', goldenHourStart: '18:37' },
  16: { sunrise: '05:58', sunset: '19:07', goldenHourStart: '18:36' },
  17: { sunrise: '05:58', sunset: '19:07', goldenHourStart: '18:36' },
  18: { sunrise: '06:02', sunset: '19:59', goldenHourStart: '19:24' },
  19: { sunrise: '06:03', sunset: '19:59', goldenHourStart: '19:23' },
};
