// Auto-generated by scripts/calc-weather.mjs
// Average weather for July trip dates (2023-2025 historical data)

export interface DayWeather {
  max: number;
  min: number;
  icon: string;
  desc: string;
}

export const weatherData: Record<number, DayWeather> = {
  0: { max: 32, min: 20, icon: '🌤️', desc: 'Малооблачно' },
  1: { max: 32, min: 21, icon: '🌦️', desc: 'Морось' },
  2: { max: 31, min: 21, icon: '🌦️', desc: 'Морось' },
  3: { max: 31, min: 22, icon: '🌦️', desc: 'Морось' },
  4: { max: 30, min: 22, icon: '🌡️', desc: '' },
  5: { max: 43, min: 28, icon: '🌤️', desc: 'Малооблачно' },
  6: { max: 32, min: 18, icon: '☁️', desc: 'Пасмурно' },
  7: { max: 35, min: 22, icon: '☁️', desc: 'Пасмурно' },
  8: { max: 36, min: 24, icon: '☁️', desc: 'Пасмурно' },
  9: { max: 31, min: 17, icon: '☁️', desc: 'Пасмурно' },
  10: { max: 33, min: 20, icon: '☁️', desc: 'Пасмурно' },
  11: { max: 26, min: 18, icon: '☁️', desc: 'Пасмурно' },
  12: { max: 24, min: 18, icon: '🌦️', desc: 'Морось' },
  13: { max: 25, min: 18, icon: '⛅', desc: 'Облачно' },
  14: { max: 28, min: 20, icon: '☁️', desc: 'Пасмурно' },
  15: { max: 27, min: 20, icon: '☁️', desc: 'Пасмурно' },
  16: { max: 27, min: 19, icon: '☁️', desc: 'Пасмурно' },
  17: { max: 26, min: 19, icon: '🌦️', desc: 'Морось' },
  18: { max: 24, min: 16, icon: '☁️', desc: 'Пасмурно' },
  19: { max: 25, min: 16, icon: '⛅', desc: 'Облачно' },
};
